# Config file for automatic testing at travis-ci.org

language: python

python:
    - 3.5
    - 3.6
    - 3.7
    - 3.8

# test with the minium required and latest versions of dependencies
env:
    - version=minimum  # asteval>=0.9.16 numpy>=1.16 scipy>=1.2 uncertainties>=3.0.1
    - version=latest  # latest version of packages available on PyPI; from requirements-dev.txt


# these packages are needed to compile SciPy, when wheels are not available on PyPI.
# installing with apt takes little time, so for now always do it to simplify the build matrix
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libgmp-dev
    - libmpfr-dev
    - libsuitesparse-dev
    - ccache
    - swig
    - libmpc-dev

# test Python nightly build
matrix:
  include:
    - python: nightly
      env:
        - version=latest
  allow_failures:
    - python: nightly
  fast_finish: true

before_install:
    - python -m pip install --upgrade pip setuptools

install:
    - if [[ $version == minimum ]]; then pip install asteval==0.9.16 numpy==1.16 scipy==1.2 uncertainties==3.0.1 pytest coverage codecov; fi
    - if [[ $version == latest ]]; then pip install -r requirements-dev.txt -U; fi
    - python setup.py install
    - pip list

script:
    - cd tests
    - coverage run --source=lmfit -m pytest
    - coverage report -m
    # test building the documentation
    - if [[ $version == latest && $TRAVIS_PYTHON_VERSION == 3.8 ]]; then cd ../doc ; make ; fi

after_success:
    - codecov
